version: "3"
services:
  staffany-backend:
    image: 1612645/staffany-frontend:v0.0.1
    restart: always
    expose:
      - "80"
    environment:
        # domain and https

      - VIRTUAL_HOST=${VIRTUAL_HOST}
      - VIRTUAL_PORT=${VIRTUAL_PORT}
      - LETSENCRYPT_HOST=${LETSENCRYPT_HOST}
      - LETSENCRYPT_EMAIL=${LETSENCRYPT_EMAIL}

networks:
  default:
    external: true
    name: ${NETWORK_NAME}
