export const QUARTER_HEIGHT = 20

export const API_PREFIX = process.env.REACT_APP_API_PREFIX

export const TYPE_SET_CURRENT_WEEK = 'TYPE_SET_CURRENT_WEEK'
export const TYPE_RESIZE_SHIFT = 'RESIZE_SHIFT'
export const TYPE_ADD_SHIFT = 'ADD_SHIFT'
export const TYPE_UPDATE_SHIFT = 'UPDATE_SHIFT'
export const TYPE_DELETE_SHIFT = 'DELETE_SHIFT'
export const TYPE_UPDATE_SHIFT_POSITION = 'UPDATE_SHIFT_POSITION'
